apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
  namespace: kubeflow
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      # nodeName: dudaji-cloud4
      volumes:
        - name: keras-cache
          hostPath:
            path: /tmp
            type: Directory
      containers:
        - name: gpu-job
          volumeMounts:
            - mountPath: /tmp/.keras
              name: keras-cache
          image: registry.dudaji.org/yoyota/forward-head-posture-cnn:86d3deb-dirty@sha256:eff0298bbceead83c24ecb71561fed5af818afca9499a3259dbf50aef1eb2d31
          args:
            - --epochs=10
            - --optimizer_name=rmsprop
            - --learning_rate=0.347217863580726
            - --decay_rate=0.9658497817740359
            - --model_dir=s3://model-dir/forward-head-posture/keras-ckpt
          envFrom:
            - secretRef:
                name: storage-credential
          resources:
            limits:
              nvidia.com/gpu: "1"
      restartPolicy: OnFailure
  backoffLimit: 4
