apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
  namespace: kubeflow
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      nodeName: dudaji-cloud4
      containers:
        - name: keras
          image: registry.dudaji.org/yoyota/forward-head-posture-cnn:v6
          args:
            - --epochs=10
            - --learning_rate=0.0228331575367195
            - --decay_rate=0.5498275322187888
            - --model_dir=s3://model-dir/forward-head-posture/keras-ckpt
          envFrom:
            - secretRef:
                name: storage-credential
          resources:
            limits:
              nvidia.com/gpu: "1"
      restartPolicy: OnFailure
  backoffLimit: 4
