apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry.dudaji.org/yoyota/forward-head-posture-cnn
deploy:
  helm:
    releases:
      - name: forward-head-posture-cnn-inception-resnet-v2-0
        namespace: kubeflow
        chartPath: helm
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST_HEX}}"
